### PR TITLE
Fix the CLI build error for Windows target

### PR DESCRIPTION
**Pull request by mertyildiran**
Introduced by https://github.com/up9inc/mizu/pull/984

```
make[2]: Entering directory '/home/mertyildiran/Documents/up9/mizu/cli'
go build  -ldflags="-s -w \
				-X 'github.com/up9inc/mizu/cli/mizu.GitCommitHash=9b475a78f9cd816080f0e633daa2940037ee63e2' \
				-X 'github.com/up9inc/mizu/cli/mizu.Branch=develop' \
				-X 'github.com/up9inc/mizu/cli/mizu.BuildTimestamp=1650460861' \
				-X 'github.com/up9inc/mizu/cli/mizu.Platform=windows_amd64' \
				-X 'github.com/up9inc/mizu/cli/mizu.Ver=0.0'" \
				-o bin/mizu_windows_amd64 mizu.go
(cd bin && shasum -a 256 mizu_windows_amd64 > mizu_windows_amd64.sha256)
# github.com/up9inc/basenine/server/lib
../../../../go/pkg/mod/github.com/up9inc/basenine/server/lib@v0.0.0-20220419100955-e2ca51087607/helpers.go:49:37: cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.Recvfrom
../../../../go/pkg/mod/github.com/up9inc/basenine/server/lib@v0.0.0-20220419100955-e2ca51087607/helpers.go:49:48: undefined: syscall.MSG_PEEK
../../../../go/pkg/mod/github.com/up9inc/basenine/server/lib@v0.0.0-20220419100955-e2ca51087607/helpers.go:49:65: undefined: syscall.MSG_DONTWAIT
shasum: mizu_windows_amd64: No such file or directory
make[2]: *** [Makefile:29: build-base] Error 1
make[2]: Leaving directory '/home/mertyildiran/Documents/up9/mizu/cli'
make[1]: *** [Makefile:25: build] Error 2
make[1]: Leaving directory '/home/mertyildiran/Documents/up9/mizu/cli'
mv: cannot stat './bin/mizu_windows_amd64': No such file or directory
```

[Build](https://github.com/up9inc/mizu/releases/tag/31.0-dev64) from CI **404**: https://github.com/up9inc/mizu/releases/download/31.0-dev64/mizu.exe

**No stable versions are affected.**

### CODE REVIEW

File: cli/config/configStructs/tapConfig.go [hunk 1]
```diff
@@ -79,10 +78,6 @@ func (config *TapConfig) GetInsertionFilter() string {
 			}
 		}
 	}
-	_, err := basenine.Parse(insertionFilter)
```
Comment (RoyUP9) [inline cli/config/configStructs/tapConfig.go:82]: why is this removed?

Comment (mertyildiran) [reply cli/config/configStructs/tapConfig.go:82]: @RoyUP9 yes, the addition of [this method](https://github.com/up9inc/basenine/blob/e2ca51087607e7e2f6688b0c4c1655b9ec552969/server/lib/helpers.go#L38-L71) to the shared library made the build error for Windows target. We don't support Windows in Basenine right now. So, I had to remove that syntax error check from there.

The user should guarantee that there are no syntax errors in the given insertion filter. If there are any, the insertion filter is ignored.

**Review by gadotroee — APPROVED** [review]

File: cli/config/configStructs/tapConfig.go (hunk 1 above)
Comment (gadotroee) [reply cli/config/configStructs/tapConfig.go:82]: @mertyildiran 
I remember that I asked for this addition and we might want to add it in the future but as long as it causes the windows binary to be broken it can be removed (more important to have valid binary and remove the small check).
so I approved this change and it can be merged before the next release.
